name: Daily Commit

on:
  schedule:
    - cron: "30 5 * * *"  # Runs daily at 05:30 AM UTC (11:00 AM IST)
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Commit by 24ds3000030@ds.study.iitm.ac.in"  # Explicitly include email in step name
        run: |
          echo "$(date)" >> daily-log.txt  # Appends the date to a file

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "24ds3000030@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Automated daily commit $(date)"
          git push
